export const DataEstadoR = [
        { category: "Ingresos de Actividades Ordinarias", values: ["", "", "", ""], editable: true },
        { category: "Costo de Ventas", values: ["", "", "", ""], editable: true },
        { category: "% Costo de Ventas / Ventas", values: ["", "", "", ""], calculated: true },
        { category: "Gastos de Ventas", values: ["", "", "", ""], editable: true },
        { category: "% Gastos de Ventas / Ventas", values: ["", "", "", ""], calculated: true },
        { category: "Gastos de Administración", values: ["", "", "", ""], editable: true },
        { category: "% Gastos de Admon / Ventas", values: ["", "", "", ""], calculated: true },
        { category: "Utilidad Op. Antes de Deprec.", values: ["", "", "", ""], calculated: true },
        { category: "% Ut. Op. Antes de Dep. / Ventas", values: ["", "", "", ""], calculated: true },
        { category: "DEPRECIACIÓN", values: ["", "", "", ""], editable: true },
        { category: "AMORTIZACIÓN", values: ["", "", "", ""], editable: true },
        { category: "Utilidad Operacional", values: ["", "", "", ""], calculated: true },
        { category: "% Utilidad Operacional / Ventas", values: ["", "", "", ""], calculated: true },
        { category: "Ingresos Financieros", values: ["", "", "", ""], editable: true },
        { category: "Gastos Financieros", values: ["", "", "", ""], editable: true },
        { category: "% Gastos Financieros / Ventas", values: ["", "", "", ""], calculated: true },
        { category: "OTROS INGRESOS Y EGRESOS", values: ["", "", "", ""], editable: true },
        { category: "CORRECCIÓN MONETARIA", values: ["", "", "", ""], editable: true },
        { category: "Utilidad Antes de Impuestos", values: ["", "", "", ""], calculated: true },
        { category: "Impuestos", values: ["", "", "", ""], editable: true },
        { category: "Utilidad Neta", values: ["", "", "", ""], calculated: true },
        { category: "% Utilidad Neta  / Ventas", values: ["", "", "", ""], calculated: true },
        { category: "OTROS RESULTADOS INTEGRALES (NETO)", values: ["", "", "", ""], editable: true },
        { category: "Total Resultado Integral del Periodo", values: ["", "", "", ""], calculated: true }
]